language: go

go:
  - 1.5
  - tip

sudo: false

services:
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - cd $GOPATH/src/github.com/docker/distribution && git checkout v2.3.0; cd $TRAVIS_BUILD_DIR
  - psql -c 'create database distribution;' -U postgres

script:
  - go test -test.v -test.short -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
